### ISSUE TITLE
What do the letters at the end of some rows mean?

### ISSUE THREAD

**Issue by UltraBob** [yquemener/THS-inventory#1]
Hi, I was diving in to try and escape rows as appropriate to allow github to parse the csv file and make it searchable, but I discovered that partway down the file there is a section with letter A-D, which may be part of the item description, or may be some 5th column with unknown meaning.  If it is desirable that I make those changes, and someone can clarify how it should be setup, I can send a pull request with an updated version that will display more nicely in github.

**Comment by UltraBob** [comment]
I talked with Ed about this it the open THS meeting a couple weeks back, but it seems like maybe he is maintaining a different list and this would not be particularly helpful to contribute to.

**Comment by yquemener** [comment]
hi! Actually this is Ed list that I am keeping there. He has not wanted to get into the git bandwagon so he usually sends it by mail to me and I upload it here.

Yes, the csv formatting has some problems but it is hard to "push" something to Ed! I am not sure what these letters mean, maybe a subbox inside the big box.
